# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from digestor import digestor_pb2 as digestor_dot_digestor__pb2


class DigestorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDigest = channel.unary_unary(
        '/digestor.Digestor/GetDigest',
        request_serializer=digestor_dot_digestor__pb2.DigestRequest.SerializeToString,
        response_deserializer=digestor_dot_digestor__pb2.DigestResponse.FromString,
        )


class DigestorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetDigest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DigestorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDigest': grpc.unary_unary_rpc_method_handler(
          servicer.GetDigest,
          request_deserializer=digestor_dot_digestor__pb2.DigestRequest.FromString,
          response_serializer=digestor_dot_digestor__pb2.DigestResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'digestor.Digestor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
