# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: digestor/digestor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='digestor/digestor.proto',
  package='digestor',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x64igestor/digestor.proto\x12\x08\x64igestor\"!\n\rDigestRequest\x12\x10\n\x08ToDigest\x18\x01 \x01(\t\" \n\x0e\x44igestResponse\x12\x0e\n\x06\x44igest\x18\x01 \x01(\t2J\n\x08\x44igestor\x12>\n\tGetDigest\x12\x17.digestor.DigestRequest\x1a\x18.digestor.DigestResponseb\x06proto3')
)




_DIGESTREQUEST = _descriptor.Descriptor(
  name='DigestRequest',
  full_name='digestor.DigestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ToDigest', full_name='digestor.DigestRequest.ToDigest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=70,
)


_DIGESTRESPONSE = _descriptor.Descriptor(
  name='DigestResponse',
  full_name='digestor.DigestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Digest', full_name='digestor.DigestResponse.Digest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['DigestRequest'] = _DIGESTREQUEST
DESCRIPTOR.message_types_by_name['DigestResponse'] = _DIGESTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DigestRequest = _reflection.GeneratedProtocolMessageType('DigestRequest', (_message.Message,), dict(
  DESCRIPTOR = _DIGESTREQUEST,
  __module__ = 'digestor.digestor_pb2'
  # @@protoc_insertion_point(class_scope:digestor.DigestRequest)
  ))
_sym_db.RegisterMessage(DigestRequest)

DigestResponse = _reflection.GeneratedProtocolMessageType('DigestResponse', (_message.Message,), dict(
  DESCRIPTOR = _DIGESTRESPONSE,
  __module__ = 'digestor.digestor_pb2'
  # @@protoc_insertion_point(class_scope:digestor.DigestResponse)
  ))
_sym_db.RegisterMessage(DigestResponse)



_DIGESTOR = _descriptor.ServiceDescriptor(
  name='Digestor',
  full_name='digestor.Digestor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=106,
  serialized_end=180,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDigest',
    full_name='digestor.Digestor.GetDigest',
    index=0,
    containing_service=None,
    input_type=_DIGESTREQUEST,
    output_type=_DIGESTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIGESTOR)

DESCRIPTOR.services_by_name['Digestor'] = _DIGESTOR

# @@protoc_insertion_point(module_scope)
